### PR TITLE
psql CLI args

### PR DESCRIPTION
**Pull request by blove319**
added ability to specify arbritrary arguments for psql command line during file import (such as variables that scripts need)
Please add this, it allows us to specify "-v blabla=abc" type variables for SQL scripts

### CODE REVIEW

**Comment by smecsia** [comment]
@blove319 Thank you for contribution. Could you please enrich the respective section in readme as well?

**Comment by blove319** [comment]
There isn't a section in readme discussing the use of importFromFile.  Would you like me to add one?

**Comment by smecsia** [comment]
@blove319 That would be nice.

**Comment by blove319** [comment]
added a couple comment lines to README illustrating how to load data from files.  (I did it as comment lines to keep the doc readable, hope that's ok).

**Comment by smecsia** [comment]
Cool, thank you.

**Pull request merged**
