### PR TITLE
append predefined data directory

### PR DESCRIPTION
**Pull request by BorzdeG**

### CODE REVIEW

**Comment by BorzdeG** [comment]
0. I try not to delete the tests without the need :)
1. These methods are still needed, because they are for tests testStep0 and testStep1

**Comment by smecsia** [comment]
@BorzdeG That would be not removal, but refactoring ;)

**Comment by BorzdeG** [comment]
Yes, I agree. In fact, redundancy is obtained in the tests.

**Comment by smecsia** [comment]
Whoops, looks like tests are now failing.

**Pull request merged**
