### PR TITLE
use logging listener

### PR DESCRIPTION
**Pull request by bigloser**
Hi,

Would you consider this patch? It gives the ability to control logging output when extracting artifacts.

Thank you!

### CODE REVIEW

**Comment by smecsia** [comment]
@bigloser 
Thanks for your contribution, and sorry for reviewing this so late. I'll check it in a few days.

**Comment by bigloser** [comment]
hey @smecsia any chance this patch can be considered? thank you!

**Comment by smecsia** [comment]
@bigloser Oh, sorry, I'm currently very busy. I had to look at this much earlier. Let's rebuild it first.

**Comment by smecsia** [comment]
rebuild this please

**Comment by smecsia** [comment]
retest this please

**Comment by smecsia** [comment]
@bigloser I've reviewed your changes. Actually, if you look at the history of the `DownloadConfigBuilder`, there was `LoggingProgressListener` already by default and it was removed in [this commit](https://github.com/bigloser/postgresql-embedded/commit/6cd715c7750af99d48ac858526775ccc2aa3997b#diff-43be1276c2f35e3a1d79b659efcf8fb8). And I see no reason to make it default again. You can always redefine it [like here](https://github.com/yandex-qatools/postgresql-embedded/blob/6cd715c7750af99d48ac858526775ccc2aa3997b/src/main/java/ru/yandex/qatools/embed/postgresql/PostgresProcess.java#L76)

**Comment by bigloser** [comment]
@smecsia Thanks for the consideration. I wanted this because I like my build console output to be clean and when using a non-forked version of this plugin there is no way to control the output. Thank you again for making this plugin.

**Comment by lanwen** [comment]
@smecsia any loggers can be turned off :)

**Pull request closed without merging**
